// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_Slider3( lv_event_t * e);
extern lv_obj_t *ui_Slider3;
void ui_event_Slider4( lv_event_t * e);
extern lv_obj_t *ui_Slider4;
extern lv_obj_t *ui_DutyLabel1;
extern lv_obj_t *ui_FreqLabel1;
extern lv_obj_t *ui_DutyLabel3;
extern lv_obj_t *ui_FreqLabel3;
void ui_event_SetFreqBTN2_Button( lv_event_t * e);
extern lv_obj_t *ui_SetFreqBTN2;
extern lv_obj_t *ui_Label1;
void ui_event_SetDutyBTN2_Button( lv_event_t * e);
extern lv_obj_t *ui_SetDutyBTN2;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_ScreenSetFreq
void ui_ScreenSetFreq_screen_init(void);
extern lv_obj_t *ui_ScreenSetFreq;
void ui_event_Panel3( lv_event_t * e);
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_ApplyLabel;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Keyboard2;
// SCREEN: ui_ScreenSetDuty
void ui_ScreenSetDuty_screen_init(void);
extern lv_obj_t *ui_ScreenSetDuty;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Panel1;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
