// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetDuty_screen_init(void)
{
ui_ScreenSetDuty = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSetDuty, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_ScreenSetDuty);
lv_obj_set_width( ui_Panel2, 230);
lv_obj_set_height( ui_Panel2, 40);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -65 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x6C5A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea2 = lv_textarea_create(ui_Panel2);
lv_obj_set_width( ui_TextArea2, 220);
lv_obj_set_height( ui_TextArea2, LV_SIZE_CONTENT);   /// 35
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
if ("0123456789"=="") lv_textarea_set_accepted_chars(ui_TextArea2, NULL);
else lv_textarea_set_accepted_chars(ui_TextArea2, "0123456789");
lv_textarea_set_max_length(ui_TextArea2,100);
lv_textarea_set_placeholder_text(ui_TextArea2,"enter value");
lv_textarea_set_one_line(ui_TextArea2,true);



ui_Panel6 = lv_obj_create(ui_ScreenSetDuty);
lv_obj_set_width( ui_Panel6, 230);
lv_obj_set_height( ui_Panel6, 190);
lv_obj_set_x( ui_Panel6, 0 );
lv_obj_set_y( ui_Panel6, 55 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x37323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0x6C5A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_Panel6);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 221);
lv_obj_set_height( ui_Keyboard1, 179);
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_Panel1 = lv_obj_create(ui_ScreenSetDuty);
lv_obj_set_width( ui_Panel1, 200);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -120 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Button1, 200);
lv_obj_set_height( ui_Button1, 45);
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x795D8F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x816D95), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Apply Duty");

lv_keyboard_set_textarea(ui_Keyboard1,ui_TextArea2);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
