// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetFreq_screen_init(void)
{
ui_ScreenSetFreq = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSetFreq, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_ScreenSetFreq);
lv_obj_set_width( ui_Panel3, 200);
lv_obj_set_height( ui_Panel3, 50);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, -120 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x795D8F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x816D95), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x6C5A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ApplyLabel = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_ApplyLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ApplyLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ApplyLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ApplyLabel,"Apply Frequency");

ui_Panel4 = lv_obj_create(ui_ScreenSetFreq);
lv_obj_set_width( ui_Panel4, 230);
lv_obj_set_height( ui_Panel4, 40);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -65 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0x6C5A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_Panel4);
lv_obj_set_width( ui_TextArea1, 220);
lv_obj_set_height( ui_TextArea1, LV_SIZE_CONTENT);   /// 35
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
if ("0123456789"=="") lv_textarea_set_accepted_chars(ui_TextArea1, NULL);
else lv_textarea_set_accepted_chars(ui_TextArea1, "0123456789");
lv_textarea_set_max_length(ui_TextArea1,98989);
lv_textarea_set_placeholder_text(ui_TextArea1,"enter value");
lv_textarea_set_one_line(ui_TextArea1,true);



ui_Panel5 = lv_obj_create(ui_ScreenSetFreq);
lv_obj_set_width( ui_Panel5, 230);
lv_obj_set_height( ui_Panel5, 190);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, 55 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x37323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel5, lv_color_hex(0x6C5A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard2 = lv_keyboard_create(ui_Panel5);
lv_keyboard_set_mode(ui_Keyboard2,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard2, 221);
lv_obj_set_height( ui_Keyboard2, 179);
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard2,ui_TextArea1);

}
