// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider3 = lv_slider_create(ui_Screen2);
lv_slider_set_range(ui_Slider3, 8,80000);
lv_slider_set_value( ui_Slider3, 32000, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider3)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider3, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider3, 30);
lv_obj_set_height( ui_Slider3, 200);
lv_obj_set_x( ui_Slider3, 80 );
lv_obj_set_y( ui_Slider3, -10 );
lv_obj_set_align( ui_Slider3, LV_ALIGN_CENTER );


ui_Slider4 = lv_slider_create(ui_Screen2);
lv_slider_set_value( ui_Slider4, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider4)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider4, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider4, 30);
lv_obj_set_height( ui_Slider4, 200);
lv_obj_set_x( ui_Slider4, -80 );
lv_obj_set_y( ui_Slider4, -10 );
lv_obj_set_align( ui_Slider4, LV_ALIGN_CENTER );


ui_DutyLabel1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_DutyLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DutyLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DutyLabel1, 0 );
lv_obj_set_y( ui_DutyLabel1, -120 );
lv_obj_set_align( ui_DutyLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DutyLabel1,"Duty, %");

ui_FreqLabel1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_FreqLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FreqLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FreqLabel1, 0 );
lv_obj_set_y( ui_FreqLabel1, -70 );
lv_obj_set_align( ui_FreqLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_FreqLabel1,"Frequency, Hz");

ui_DutyLabel3 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_DutyLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DutyLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DutyLabel3, 0 );
lv_obj_set_y( ui_DutyLabel3, -100 );
lv_obj_set_align( ui_DutyLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_DutyLabel3,"50");

ui_FreqLabel3 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_FreqLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FreqLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FreqLabel3, 0 );
lv_obj_set_y( ui_FreqLabel3, -50 );
lv_obj_set_align( ui_FreqLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_FreqLabel3,"32000");

ui_SetFreqBTN2 = ui_Button_create(ui_Screen2);
lv_obj_set_x( ui_SetFreqBTN2, 0 );
lv_obj_set_y( ui_SetFreqBTN2, 0 );

ui_Label1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"SET FREQ");

ui_SetDutyBTN2 = ui_Button_create(ui_Screen2);
lv_obj_set_x( ui_SetDutyBTN2, 0 );
lv_obj_set_y( ui_SetDutyBTN2, 65 );

ui_Label2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, 65 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"SET DUTY");

lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SetFreqBTN2, ui_event_SetFreqBTN2_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SetDutyBTN2, ui_event_SetDutyBTN2_Button, LV_EVENT_ALL, NULL);

}
